controller_manager:
  ros__parameters:
    update_rate: 100

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    forward_position_controller:
      type: forward_command_controller/ForwardCommandController

/mixer/controller_manager:
  ros__parameters:
    update_rate: 100

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    forward_position_controller:
      type: forward_command_controller/ForwardCommandController

forward_position_controller:
  ros__parameters:
    joints:
      - sun_joint
      - shroud_joint
      - planet_1_orbit_joint
      - planet_1_spin_joint
      - planet_2_orbit_joint
      - planet_2_spin_joint
    interface_name: position

/mixer/forward_position_controller:
  ros__parameters:
    joints:
      - sun_joint
      - shroud_joint
      - planet_1_orbit_joint
      - planet_1_spin_joint
      - planet_2_orbit_joint
      - planet_2_spin_joint
    interface_name: position

joint_state_broadcaster:
  ros__parameters:
    use_local_topics: true

/mixer/joint_state_broadcaster:
  ros__parameters:
    use_local_topics: true